@startuml
class logic.Order {
- ArrayList<OrderItem> orderItemList
- {static} int totalOrderCount
- int orderNumber
+ OrderItem addItem(Item,int)
+ int calculateOrderTotalPrice()
+ {static} int getTotalOrderCount()
+ {static} void resetTotalOrderCount()
+ int getOrderNumber()
+ ArrayList<OrderItem> getOrderItemList()
}


class application.MisaShop {
- {static} ArrayList<Item> itemList
- {static} ArrayList<Order> orderList
- {static} boolean isEnd
- {static} Scanner kb
+ {static} void main(String[])
+ {static} void addItemToOrder(Order,int,int)
+ {static} boolean addNewItem(String,int)
+ {static} boolean isItemExisted(String)
- {static} void handleAddItem()
- {static} void handleCreateNewOrder()
- {static} void showAllItems()
- {static} void showAllOrder()
+ {static} ArrayList<Order> getOrderList()
+ {static} void addBlankOrder()
+ {static} void initializeData()
}


class logic.OrderItem {
~ Item item
~ int itemAmount
+ void increaseItemAmount(int)
+ int calculateTotalPrice()
+ Item getItem()
+ void setItem(Item)
+ int getItemAmount()
+ void setItemAmount(int)
}


class logic.Item {
~ String name
~ int PricePerPiece
+ String getName()
+ int getPricePerPiece()
+ void setName(String)
+ void setPricePerPiece(int)
}


@enduml